name: GitHub Actions Demo
on:
  push:
    branches: [london-class-8/craig-dsilva]
  pull_request:
    branches: [london-class-8/craig-dsilva]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install modules
        run: npm install
      - name: Test
        run: npm test
